export default [
  {
      idpost: "22",
      judul: "Terbentuknya Cincin Saturnus",
      isi_post: "<p>Seperti yang kita semua ketahui, dalam tata surya ada satu matahari, 4 planet dalam, dan 4 planet luar. Yang menjadi planet dalam adalah Merkurius, Venus, Bumi, dan Mars, sedangkan planet luar adalah Jupiter, Saturnus, Uranus, dan Neptunus.  Merkurius, Venus, Bumi, dan Mars dikategorikan sebagai planet dalam karena berada di dalam sabuk asteroid, sedangkan Jupiter, Saturnus, Uranus, dan Neptunus sebaliknya. </p>\r\n<p>Setiap planet memiliki ciri khasnya sendiri-sendiri, seperti Merkurius planet terdekat dengan matahari, Venus planet terpanas, Bumi satu-satunya yang bisa dihuni, Jupiter planet terbesar, dan Saturnus dengan cincinnya. Tapi pernahkah terbesit di pikiran kawan-kawan mengapa hanya saturnus yang memiliki cincin?</p>\r\n<p>Sejak pertama kali terlihat dalam bidikan teleskop Galileo pada 1610, Saturnus selalu menarik perhatian berkat cincin yang mengitarinya. Kemudian selama empat abad modern, para astronom meneliti cincin misterius tersebut. Hingga akhirnya pada Januari 2011 terungkaplah semuanya.</p>\r\n<p>Robin Canup dari Southwest Research Institute di Boulder, Coloradu mengemukakan suatu teori baru mengenai pembentukan cincin Saturnus. Menurut Canup, cincin tersebut merupakan sisa-sisa benda langit yang dahulunya mengitari planet tersebut. </p>\r\n<p>Ribuan bahkan jutaan benda langit kemudian terkoyak lalu berbaur mengitari Saturnus karena gravitasinya, sehingga terbentuklah lingkaran yang menyerupai cincin apabila dilihat dari jauh. Diprediksi cincin saturnus telah ada sejak 4,5 miliar tahun yang lalu. </p>\r\n<p>Pada mulanya, satelit alami Saturnus berputar ke dalam. Setelah itu, gravitasi Saturnus merobek lapisan luarnya dengan perlahan, sehingga membuat penampakannya seperti saat ini. Setelah 10.000 tahun, satelit itu hancur dan melebur menjadi bebatuan kecil yang tampak menyerupai cincin.</p>\r\n<p>Begitulah awal mulai bagaimana cincin yang menjadi ciri khas dari suatu planet yang bernama Saturnus dapat terbentuk. Jadi jangan penasaran lagi ya kawan!</p>",
      file_gambar: "saturn-ring.jpg",
      tgl_insert: "2020-10-24 13:28:10",
      tgl_update: "2020-10-24 13:32:22",
      idkategori: "4",
      idpenulis: "5",
      nama_kategori: "sci & tech",
      nama: "Adonay Cahya P",
      email: "adonaycahyap@gmail.com",
      password: "32c8d65308c3af9403ecd4ad013bb3279ed47883",
      alamat: "Jalan Duku 7 No. 10",
      kota: "Semarang",
      no_telp: "081334281490"
  },
  {
      idpost: "21",
      judul: "Kenapa sih Awan Altocumulus Lenticular Bisa Terjadi?",
      isi_post: "<p>Awan Altocumulus lenticular atau yang sering disebut awan topi di kalangan para pendaki ataupun masyarakat lokal. Meskipun indah, awan ini merupakan mimpi buruk bagi para pendaki. Menurut astronom amatir Marufin Sudibyo, awan ini adalah awan stasioner (tak bergerak) yang terbentuk saat aliran udara menubruk satu penghalang besar, sehingga membentuk pusaran stasioner. Penghalang ini dapat berupa puncak gunung ataupun Kawasan dengan tekanan udara lokal lebih tinggi.</p>\r\n<p>Meskipun indah awan ini merupakan mimpi buruk para pendaki gunung. Awan topi ini merupakan pertanda badai atau angin kencang sedang terjadi di dalam awan tersebut, seperti yang kita ketahui sendiri badai ataupun angin kencang adalah salah satu yang paling dihindari oleh para pendaki. Tetapi tenang, badai tersebut hanyalah terjadi di dalam awan, kawasan yang berada di sekitar awan tersebut akan tetap aman dari terjangan badai, hanya akan terjadi suhu udara yang cenderung lebih dingin dari biasanya.</p>",
      file_gambar: "lenticular.jpg",
      tgl_insert: "2020-10-24 13:08:50",
      tgl_update: "2020-10-24 13:17:31",
      idkategori: "2",
      idpenulis: "1",
      nama_kategori: "travel",
      nama: "Nadia",
      email: "annisanadianeyla@gmail.com",
      password: "9ba21ecb3fa869932b657005c990d9a2406a32d5",
      alamat: "Puri Harapan C18 No. 25",
      kota: "Bekasi",
      no_telp: "087839461809"
  },
  {
      idpost: "20",
      judul: "Life Hacks: Berkebun di Lahan Sempit",
      isi_post: "<p>Metode Tabulampot</p>\r\n<p>Kata Tabulampot merupakan singkatan dari \"Tanaman Buah Dalam Pot\". Metode ini sering digunakan untuk berkebun pada lahan yang sempit. Untuk menerapkan metode tabulampot, media tanam yang perlu disediakan, yaitu tanah, kompos, dan sekam. Ketiga komposisi tersebut harus seimbang dan dibagi rata. Media tanam dengan metode ini harus mampu menyimpan air dan memasok nutrisi bagi tanaman. Wadah yang digunakan dapat berupa dari bahan, tanah liat, plastik, kayu, logam, atau semen.</p> \r\n<p>Metode Vertikultur</p>\r\n<p>Metode vertikultur memanfaatkan bidang vertical dan bercocok tanam dilakukan secara bertingkat. Media vertikultur cocok dalam membudidayakan tanaman sayur. Modelnya, tanaman dapat digantung, tempel, tegak, ataupun rak.  Media tanam yang digunakan dapat berupa tanah, kompos, dan sekam. Untuk penyiraman, air harus dialirkan dari bagian atas pipa paralon. </p> \r\n<p>Metode Aeroponik</p> \r\n<p>Aeroponik berasal dari kata \"aero\" yang berarti udara dan \"ponus\" yang berarti daya. Metode aeroponik memanfaatkan udara sebagai media tanam utamanya. Akar tanamannya akan menggantung di atas udara. Air yang digunakan cukup disemprotkan langsung pada akar tanaman. Dengan cara ini, nutrisi yang ada akan langsung diserap dan dialirkan langsung ke semua bagian dari tanaman, mulai dari batang hingga daun. Keuntungan yang didapatkan jika menggunakan metode ini, yaitu  tanaman akan tumbuh lebih cepat, sehingga produksinya menjadi sangat tinggi.</p>\r\n<p>Ganti Pot dengan Kantong Tanaman</p>\r\n<p>Menanam dengan pot cenderung membutuhkan banyak tempat, kamu bisa menggantinya dengan kantong-kantong tanaman. Kantong tersebut kemudian diisi dengan tanah dan ditanami tumbuhan. Untuk memaksimalkan ruang sempit, kantong bisa dipasang dengan cara digantung atau dipasang di dinding.</p>\r\n<p>Bikin Kebun Vertical</p>\r\n<p>Berkebun dengan cara vertikal sangat cocok dengan kondisi rumah yang lahannya sangat terbatas. Kamu bisa berkreasi dengan kebun vertikal dengan meletakan tanaman di dinding, pagar, atau papan.</p>\r\n<p>Kebun Sayur Sekaligus Penghias Ruangan</p>\r\n<p>Tanaman hias nggak selalu bunga berwarna-warni. Tanaman lain seperti bumbu dapur juga bisa menjadi penghias ruangan. Kamu bisa letakkan pot-pot kecil berisi tanaman bumbu dapur seperti daun mint atau basil di sudut-sudut ruangan atau dekat jendela dapur.</p>\r\n<p>Manfaatkan Toples Bekas</p>\r\n<p>Biasanya banyak toples bekas yang tidak digunakan di rumah. Kamu bisa memanfaatkannya menjadi media tanam. Tanaman-tanaman penyedap rasa seperti basil, rosemary, atau oregano cocok ditanam di toples bekas.</p>\r\n<p>Hidroponik</p>\r\n<p>Hidroponik adalah metode menanam tanpa menggunakan tanah. Cara menanam hidroponik lebih menekankan pada pemenuhan nutrisi tanaman. Dengan media tanam pot atau pipa, berkebun bisa lebih praktis. Kelebihan dari hidroponik adalah bisa diletakan di dalam atau luar ruangan.</p>\r\n<p>Satu Pot Besar Beberapa Tanaman</p>\r\n<p>Mungkin kamu malas atau kerepotan merawat tanaman dengan jumlah pot yang banyak. Meletakan beberapa tanaman dalam satu pot besar bisa menjadi solusi terbaik. Siapkan satu pot berukuran besar, lalu tanam dengan beragam jenis.</p>\r\n<p>Gantungin aja</p>\r\n<p>Untuk memanfaatkan dimensi ruangan, kamu bisa menggantungkan tanaman seperti misalnya di dapur. Tentu saja pastikan tali penggantung kuat menahan beban tanaman dan pot.</p>",
      file_gambar: "hydroponics.jpg",
      tgl_insert: "2020-10-24 13:01:49",
      tgl_update: "2020-10-24 19:42:38",
      idkategori: "1",
      idpenulis: "1",
      nama_kategori: "life",
      nama: "Nadia",
      email: "annisanadianeyla@gmail.com",
      password: "9ba21ecb3fa869932b657005c990d9a2406a32d5",
      alamat: "Puri Harapan C18 No. 25",
      kota: "Bekasi",
      no_telp: "087839461809"
  },
]